import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { ConvexClientProvider } from '@/components/providers/ConvexClientProvider';
const jetbrainsMono = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={jetbrainsMono.variable} suppressHydrationWarning>
			<body className={`${jetbrainsMono.variable} antialiased`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem
					disableTransitionOnChange
				>
					<ConvexClientProvider>
						{children}
						<ToastContainer />
					</ConvexClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
